name: release-create

on:
  push:
    branches:
      - master

jobs:
  release-create:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: 1pm/gh-action-release-by-commit@v1.0.0
        with:
          title: "Release: $version"
          tag: "v$semver"
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge to Production
        if: ${{ steps.create_release.outputs.released }}
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: ${{ steps.create_release.outputs.id }}
          target_branch: production
