name: release-create

on:
  push:
    branches:
      - production

jobs:
  release-create:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Release
        uses: 1pm/gh-action-release-by-commit@v1.0.0
        with:
          title: "Release: $version"
          tag: "v$semver"
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
